Run 2: install and restart proceed but see "No module named 'app'" message.
Added flask-wtf the to the release requirements file, and now on
rastarting the server I see:
  ...
  ModuleNotFoundError: No module named 'app'
  unable to load app 0 (mountpoint='') (callable not found or import error)
  ...

Removed verbosity in scp command and switched to Python 3.10, but don't
currently have an effectve solution. Reading about uwsgi configuration,
which I was so_ hoping not to have to do.